services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - webapp
      - gateway
      - botapi
      - multiplayer
    networks:
      - monitor-net

  users:
    image: ghcr.io/arquisoft/yovi_en2c-users:latest
    container_name: users
    environment:
      - MONGODB_URI=${MONGODB_URI}
    expose:
      - "3000"
    networks:
      - monitor-net

  authentication:
    image: ghcr.io/arquisoft/yovi_en2c-authentication:latest
    container_name: authentication
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES=${JWT_EXPIRES}
      - USERS_SERVICE_URL=http://users:3000
      - PORT=5000
    depends_on:
      - users
    expose:
      - "5000"
    networks:
      - monitor-net

  webapp:
    image: ghcr.io/arquisoft/yovi_en2c-webapp:latest
    container_name: webapp
    expose:
      - "80"
    depends_on:
      - gateway
    networks:
      - monitor-net

  multiplayer:
    image: ghcr.io/arquisoft/yovi_en2c-multiplayer:latest
    container_name: multiplayer
    environment:
      - GAMEY_BASE_URL=http://gamey:4000
      - PORT=7000
    depends_on:
      - gamey
    expose:
      - "7000"
    networks:
      - monitor-net

  gateway:
    image: ghcr.io/arquisoft/yovi_en2c-gateway:latest
    container_name: gateway
    environment:
      - AUTH_BASE_URL=http://authentication:5000
      - GAMEY_BASE_URL=http://gamey:4000
      - MULTIPLAYER_BASE_URL=http://multiplayer:7000
      - USERS_BASE_URL=http://users:3000
      - PORT=8080
    depends_on:
      - authentication
      - gamey
      - multiplayer
    expose:
      - "8080"
    networks:
      - monitor-net

  botapi:
    image: ghcr.io/arquisoft/yovi_en2c-botapi:latest
    container_name: botapi
    environment:
      - GAMEY_BASE_URL=http://gamey:4000
      - GAMEY_API_VERSION=v1
      - PORT=4001
    depends_on:
      - gamey
    expose:
      - "4001"
    networks:
      - monitor-net

  gamey:
    image: ghcr.io/arquisoft/yovi_en2c-gamey:latest
    container_name: gamey
    expose:
      - "4000"
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./users/monitoring/prometheus:/etc/prometheus:ro
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "9091:3000"
    volumes:
      - ./users/monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge