services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - webapp
      - gateway
      - botapi
    networks:
      - monitor-net

  users:
    build: ./users
    container_name: users
    image: ghcr.io/arquisoft/yovi_en2c-users:latest
    environment:
      - MONGODB_URI=${MONGODB_URI}
    expose:
      - "3000"
    networks:
      - monitor-net

  authentication:
    build: ./authentication
    container_name: authentication
    image: ghcr.io/arquisoft/yovi_en2c-authentication:latest
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES=${JWT_EXPIRES}
      - USERS_SERVICE_URL=http://users:3000
      - PORT=5000
    depends_on:
      - users
    expose:
      - "5000"
    networks:
      - monitor-net

  webapp:
    build:
      context: ./webapp
      args:
        - VITE_API_URL=/api
    container_name: webapp
    image: ghcr.io/arquisoft/yovi_en2c-webapp:latest
    expose:
      - "80"
    depends_on:
      - gateway
    networks:
      - monitor-net

  gateway:
    build: ./gateway
    container_name: gateway
    image: ghcr.io/arquisoft/yovi_en2c-gateway:latest
    environment:
      - AUTH_BASE_URL=http://authentication:5000
      - GAMEY_BASE_URL=http://gamey:4000
      - PORT=8080
    depends_on:
      - authentication
      - gamey
    expose:
      - "8080"
    networks:
      - monitor-net

  botapi:
    build: ./botapi
    container_name: botapi
    image: ghcr.io/arquisoft/yovi_en2c-botapi:latest
    environment:
      - GAMEY_BASE_URL=http://gamey:4000
      - GAMEY_API_VERSION=v1
      - PORT=4001
    depends_on:
      - gamey
    expose:
      - "4001"
    networks:
      - monitor-net

  gamey:
    build: ./gamey
    container_name: gamey
    image: ghcr.io/arquisoft/yovi_en2c-gamey:latest
    expose:
      - "4000"
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./users/monitoring/prometheus:/etc/prometheus
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "9091:3000"
    volumes:
      - ./users/monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge