ifndef::imagesdir[:imagesdir: ../images]

[[section-concepts]]
== Cross-cutting Concepts

=== Internationalization
For the application to be more accessible to a wider range of uses, internationalization was implemented for the languages of english and spanish.

=== Testing
Testing every piece of code implemented is critical in order to achieve a sustainable system an lowering the risk of having errors and bugs. For this not only do we have mock tests for the source code, but the Github repository will also use sonarqube to ensure proper coverage.

=== Security
The security features are heavily related to the previous point, as the lowerment of risks and possible breaches is reinforced by testing. Nevertheless, it is also worth adding that the use of a virtual machine and the isolation of the docker containers will also contribute to make the system safer overall, as well as the possible use of Github secrets in the deployment of the application.

=== Gateway
The gateway service is an architectural feature that works as a bridge between the different microservices implemented, being its main function connecting the gamey service (which is in charge of the functionality of the Game Y) and the webapp, which is the GUI that allows the user to interact with the game and play it.
