server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Reenvía cualquier ruta desconocida a index.html para que React Router la gestione
    location / {
        try_files $uri $uri/ /index.html;
    }
}